"""remove_redundant_event_id_from_assignment

Revision ID: 0b87706ec619
Revises: d1d35041d5ed
Create Date: 2026-02-21 18:32:46.000593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b87706ec619'
down_revision: Union[str, Sequence[str], None] = 'd1d35041d5ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('resource_assignments_event_id_fkey'), 'resource_assignments', type_='foreignkey')
    op.drop_column('resource_assignments', 'event_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_assignments', sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('resource_assignments_event_id_fkey'), 'resource_assignments', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###
