"""make_resource_name_unique

Revision ID: 363df46ecc9e
Revises: cd473e68d53c
Create Date: 2026-02-21 17:41:05.940906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '363df46ecc9e'
down_revision: Union[str, Sequence[str], None] = 'cd473e68d53c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_resource_items_name'), 'resource_items', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_items_name'), table_name='resource_items')
    # ### end Alembic commands ###
