"""consolidate_resource_lifecycle

Revision ID: 4ea092102022
Revises: 363df46ecc9e
Create Date: 2026-02-21 18:07:08.765571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ea092102022'
down_revision: Union[str, Sequence[str], None] = '363df46ecc9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_assignments_id'), table_name='event_assignments')
    op.drop_table('event_assignments')
    op.drop_index(op.f('ix_departure_items_id'), table_name='departure_items')
    op.drop_table('departure_items')
    op.drop_index(op.f('ix_warehouse_departures_id'), table_name='warehouse_departures')
    op.drop_table('warehouse_departures')
    op.add_column('resource_assignments', sa.Column('status', sa.String(), nullable=True))
    op.add_column('resource_assignments', sa.Column('delivery_date', sa.Date(), nullable=True))
    op.add_column('resource_assignments', sa.Column('return_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource_assignments', 'return_date')
    op.drop_column('resource_assignments', 'delivery_date')
    op.drop_column('resource_assignments', 'status')
    op.create_table('warehouse_departures',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('departure_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('responsible_person_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['responsible_person_id'], ['persons.id'], name=op.f('warehouse_departures_responsible_person_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('warehouse_departures_pkey'))
    )
    op.create_index(op.f('ix_warehouse_departures_id'), 'warehouse_departures', ['id'], unique=False)
    op.create_table('event_assignments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('departure_item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['departure_item_id'], ['departure_items.id'], name=op.f('event_assignments_departure_item_id_fkey')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('event_assignments_event_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('event_assignments_pkey'))
    )
    op.create_index(op.f('ix_event_assignments_id'), 'event_assignments', ['id'], unique=False)
    op.create_table('departure_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('departure_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('return_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['departure_id'], ['warehouse_departures.id'], name=op.f('departure_items_departure_id_fkey')),
    sa.ForeignKeyConstraint(['item_id'], ['resource_items.id'], name=op.f('departure_items_item_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('departure_items_pkey'))
    )
    op.create_index(op.f('ix_departure_items_id'), 'departure_items', ['id'], unique=False)
    # ### end Alembic commands ###
