"""Initial migration

Revision ID: 5fa6a5f1808b
Revises: 
Create Date: 2026-02-21 11:58:48.915687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa6a5f1808b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_name'), 'events', ['name'], unique=False)
    op.create_table('resource_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_categories_id'), 'resource_categories', ['id'], unique=False)
    op.create_index(op.f('ix_resource_categories_name'), 'resource_categories', ['name'], unique=True)
    op.create_table('warehouse_departures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('departure_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('responsible_person', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_departures_id'), 'warehouse_departures', ['id'], unique=False)
    op.create_table('resource_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['resource_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_items_id'), 'resource_items', ['id'], unique=False)
    op.create_index(op.f('ix_resource_items_serial_number'), 'resource_items', ['serial_number'], unique=True)
    op.create_table('departure_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('departure_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['departure_id'], ['warehouse_departures.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['resource_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departure_items_id'), 'departure_items', ['id'], unique=False)
    op.create_table('event_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('departure_item_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['departure_item_id'], ['departure_items.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_assignments_id'), 'event_assignments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_assignments_id'), table_name='event_assignments')
    op.drop_table('event_assignments')
    op.drop_index(op.f('ix_departure_items_id'), table_name='departure_items')
    op.drop_table('departure_items')
    op.drop_index(op.f('ix_resource_items_serial_number'), table_name='resource_items')
    op.drop_index(op.f('ix_resource_items_id'), table_name='resource_items')
    op.drop_table('resource_items')
    op.drop_index(op.f('ix_warehouse_departures_id'), table_name='warehouse_departures')
    op.drop_table('warehouse_departures')
    op.drop_index(op.f('ix_resource_categories_name'), table_name='resource_categories')
    op.drop_index(op.f('ix_resource_categories_id'), table_name='resource_categories')
    op.drop_table('resource_categories')
    op.drop_index(op.f('ix_events_name'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
