"""refactor_resource_tracking_and_dates

Revision ID: 609262184d58
Revises: ef08dad15e3e
Create Date: 2026-02-21 17:09:02.804719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '609262184d58'
down_revision: Union[str, Sequence[str], None] = 'ef08dad15e3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('assigned_quantity', sa.Integer(), nullable=False),
    sa.Column('assignment_date', sa.Date(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['resource_items.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_assignments_id'), 'resource_assignments', ['id'], unique=False)
    op.add_column('events', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('events', sa.Column('end_date', sa.Date(), nullable=True))
    op.drop_column('events', 'date')
    op.add_column('resource_items', sa.Column('available_quantity', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_resource_items_serial_number'), table_name='resource_items')
    op.create_index(op.f('ix_resource_items_serial_number'), 'resource_items', ['serial_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_items_serial_number'), table_name='resource_items')
    op.create_index(op.f('ix_resource_items_serial_number'), 'resource_items', ['serial_number'], unique=True)
    op.drop_column('resource_items', 'available_quantity')
    op.add_column('events', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('events', 'end_date')
    op.drop_column('events', 'start_date')
    op.drop_index(op.f('ix_resource_assignments_id'), table_name='resource_assignments')
    op.drop_table('resource_assignments')
    # ### end Alembic commands ###
