"""rename_resource_item_to_item

Revision ID: 7b7ded4ee2ab
Revises: e4b2acefe02e
Create Date: 2026-02-21 18:50:35.529959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b7ded4ee2ab'
down_revision: Union[str, Sequence[str], None] = 'e4b2acefe02e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Rename table resource_items to items
    op.rename_table('resource_items', 'items')
    
    # Rename indexes
    op.execute('ALTER INDEX ix_resource_items_id RENAME TO ix_items_id')
    op.execute('ALTER INDEX ix_resource_items_name RENAME TO ix_items_name')
    
    # Update foreign key in warehouse_stocks to point to renamed table
    op.drop_constraint('warehouse_stocks_item_id_fkey', 'warehouse_stocks', type_='foreignkey')
    op.create_foreign_key(None, 'warehouse_stocks', 'items', ['item_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warehouse_stocks', type_='foreignkey')
    op.create_foreign_key(op.f('warehouse_stocks_item_id_fkey'), 'warehouse_stocks', 'resource_items', ['item_id'], ['id'])
    op.alter_column('events', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('resource_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('resource_items_pkey'))
    )
    op.create_index(op.f('ix_resource_items_name'), 'resource_items', ['name'], unique=True)
    op.create_index(op.f('ix_resource_items_id'), 'resource_items', ['id'], unique=False)
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
