"""add_role_entity

Revision ID: 9589e450dff3
Revises: 7b7ded4ee2ab
Create Date: 2026-02-21 19:31:12.707755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9589e450dff3'
down_revision: Union[str, Sequence[str], None] = '7b7ded4ee2ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.add_column('event_participations', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event_participations', 'roles', ['role_id'], ['id'])
    op.drop_column('event_participations', 'role')
    op.alter_column('events', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('event_participations', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'event_participations', type_='foreignkey')
    op.drop_column('event_participations', 'role_id')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
