"""add_multi_warehouse_support

Revision ID: 982e2cca149a
Revises: 4ea092102022
Create Date: 2026-02-21 18:19:17.197891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '982e2cca149a'
down_revision: Union[str, Sequence[str], None] = '4ea092102022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)
    op.create_index(op.f('ix_warehouses_name'), 'warehouses', ['name'], unique=True)
    op.create_table('warehouse_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['resource_items.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_stocks_id'), 'warehouse_stocks', ['id'], unique=False)
    op.add_column('resource_assignments', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'resource_assignments', 'warehouses', ['warehouse_id'], ['id'])
    op.drop_column('resource_items', 'status')
    op.drop_column('resource_items', 'available_quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_items', sa.Column('available_quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('resource_items', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'resource_assignments', type_='foreignkey')
    op.drop_column('resource_assignments', 'warehouse_id')
    op.drop_index(op.f('ix_warehouse_stocks_id'), table_name='warehouse_stocks')
    op.drop_table('warehouse_stocks')
    op.drop_index(op.f('ix_warehouses_name'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.drop_table('warehouses')
    # ### end Alembic commands ###
