"""link_assignment_to_warehouse_stock

Revision ID: a6d254aa333e
Revises: 982e2cca149a
Create Date: 2026-02-21 18:26:49.096322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6d254aa333e'
down_revision: Union[str, Sequence[str], None] = '982e2cca149a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_assignments', sa.Column('warehouse_stock_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('resource_assignments_warehouse_id_fkey'), 'resource_assignments', type_='foreignkey')
    op.drop_constraint(op.f('resource_assignments_item_id_fkey'), 'resource_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'resource_assignments', 'warehouse_stocks', ['warehouse_stock_id'], ['id'])
    op.drop_column('resource_assignments', 'item_id')
    op.drop_column('resource_assignments', 'warehouse_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_assignments', sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('resource_assignments', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'resource_assignments', type_='foreignkey')
    op.create_foreign_key(op.f('resource_assignments_item_id_fkey'), 'resource_assignments', 'resource_items', ['item_id'], ['id'])
    op.create_foreign_key(op.f('resource_assignments_warehouse_id_fkey'), 'resource_assignments', 'warehouses', ['warehouse_id'], ['id'])
    op.drop_column('resource_assignments', 'warehouse_stock_id')
    # ### end Alembic commands ###
