"""remove_category_entity

Revision ID: c9f3f660626f
Revises: 609262184d58
Create Date: 2026-02-21 17:11:44.421362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9f3f660626f'
down_revision: Union[str, Sequence[str], None] = '609262184d58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('resource_items_category_id_fkey'), 'resource_items', type_='foreignkey')
    op.drop_column('resource_items', 'category_id')
    op.drop_index(op.f('ix_resource_categories_id'), table_name='resource_categories')
    op.drop_index(op.f('ix_resource_categories_name'), table_name='resource_categories')
    op.drop_table('resource_categories')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_items', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('resource_items_category_id_fkey'), 'resource_items', 'resource_categories', ['category_id'], ['id'])
    op.create_table('resource_categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('resource_categories_pkey'))
    )
    op.create_index(op.f('ix_resource_categories_name'), 'resource_categories', ['name'], unique=True)
    op.create_index(op.f('ix_resource_categories_id'), 'resource_categories', ['id'], unique=False)
    # ### end Alembic commands ###
