"""move_serial_number_to_assignment

Revision ID: cd473e68d53c
Revises: c9f3f660626f
Create Date: 2026-02-21 17:21:45.059439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd473e68d53c'
down_revision: Union[str, Sequence[str], None] = 'c9f3f660626f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_assignments', sa.Column('serial_number', sa.String(), nullable=True))
    op.drop_index(op.f('ix_resource_items_serial_number'), table_name='resource_items')
    op.drop_column('resource_items', 'serial_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_items', sa.Column('serial_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_resource_items_serial_number'), 'resource_items', ['serial_number'], unique=False)
    op.drop_column('resource_assignments', 'serial_number')
    # ### end Alembic commands ###
