"""add_name_to_resource_item

Revision ID: cf59c9aadead
Revises: 5fa6a5f1808b
Create Date: 2026-02-21 12:56:31.537699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf59c9aadead'
down_revision: Union[str, Sequence[str], None] = '5fa6a5f1808b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_items', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource_items', 'name')
    # ### end Alembic commands ###
