"""refactor_personnel_to_participation

Revision ID: d1d35041d5ed
Revises: a6d254aa333e
Create Date: 2026-02-21 18:30:01.727433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1d35041d5ed'
down_revision: Union[str, Sequence[str], None] = 'a6d254aa333e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_participations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_participations_id'), 'event_participations', ['id'], unique=False)
    op.drop_table('event_personnel')
    op.add_column('resource_assignments', sa.Column('participation_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('resource_assignments_person_id_fkey'), 'resource_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'resource_assignments', 'event_participations', ['participation_id'], ['id'])
    op.drop_column('resource_assignments', 'person_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_assignments', sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'resource_assignments', type_='foreignkey')
    op.create_foreign_key(op.f('resource_assignments_person_id_fkey'), 'resource_assignments', 'persons', ['person_id'], ['id'])
    op.drop_column('resource_assignments', 'participation_id')
    op.create_table('event_personnel',
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('event_personnel_event_id_fkey')),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('event_personnel_person_id_fkey')),
    sa.PrimaryKeyConstraint('event_id', 'person_id', name=op.f('event_personnel_pkey'))
    )
    op.drop_index(op.f('ix_event_participations_id'), table_name='event_participations')
    op.drop_table('event_participations')
    # ### end Alembic commands ###
