"""add_person_entity

Revision ID: ef08dad15e3e
Revises: cf59c9aadead
Create Date: 2026-02-21 17:03:42.640400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef08dad15e3e'
down_revision: Union[str, Sequence[str], None] = 'cf59c9aadead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('identification_number', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persons_full_name'), 'persons', ['full_name'], unique=False)
    op.create_index(op.f('ix_persons_id'), 'persons', ['id'], unique=False)
    op.create_index(op.f('ix_persons_identification_number'), 'persons', ['identification_number'], unique=True)
    op.create_table('event_personnel',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'person_id')
    )
    op.add_column('warehouse_departures', sa.Column('responsible_person_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'warehouse_departures', 'persons', ['responsible_person_id'], ['id'])
    op.drop_column('warehouse_departures', 'responsible_person')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse_departures', sa.Column('responsible_person', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'warehouse_departures', type_='foreignkey')
    op.drop_column('warehouse_departures', 'responsible_person_id')
    op.drop_table('event_personnel')
    op.drop_index(op.f('ix_persons_identification_number'), table_name='persons')
    op.drop_index(op.f('ix_persons_id'), table_name='persons')
    op.drop_index(op.f('ix_persons_full_name'), table_name='persons')
    op.drop_table('persons')
    # ### end Alembic commands ###
